{{- if .Values.rbac.create -}}
# VerneMQ needs to query k8s apiserver to list the other pods in the namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vernemq.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "vernemq.name" . }}
    helm.sh/chart: {{ include "vernemq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get"]
{{- end -}}